# Generated by Django 2.1.3 on 2018-11-17 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Binder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('zip', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='binder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades.User'),
        ),
    ]
