# Generated by Django 2.1.3 on 2018-11-17 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trades', '0002_user_join_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='card name')),
                ('expansion', models.CharField(max_length=3, verbose_name='expansion')),
                ('condition', models.CharField(max_length=2, verbose_name='condition')),
                ('foil', models.BooleanField(default=False, verbose_name='foil')),
            ],
        ),
        migrations.RemoveField(
            model_name='binder',
            name='user',
        ),
        migrations.AddField(
            model_name='binder',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='card',
            name='binder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trades.Binder'),
        ),
    ]
